INFO 2020-12-06 18:54:12,874 root : Сервер доступний. Час на сервері: 2020-12-06
INFO 2020-12-06 18:54:12,874 root : Запитувана сторінка: : http://localhost:8000/health/
INFO 2020-12-06 18:54:12,874 root : Відповідь сервера містить наступні поля:
INFO 2020-12-06 18:54:12,874 root : Ключ: date, Значення: 2020-12-06
INFO 2020-12-06 18:54:12,874 root : Ключ: current_page, Значення: http://localhost:8000/health/
INFO 2020-12-06 18:54:12,874 root : Ключ: server_info, Значення: 36f85efc6e65
INFO 2020-12-06 18:54:12,875 root : Ключ: client_info, Значення: {'user_agent': 'python-requests/2.24.0', 'user_ip': '172.18.0.1', 'user_host': ''}
ERROR 2020-12-06 18:55:12,917 root : Сервер недоступний
ERROR 2020-12-06 18:55:12,917 root : Помилка: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /health (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff193cfb1c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
ERROR 2020-12-06 18:55:12,917 root : http://localhost:8000/health
